docker_yum_repo_url: https://download.docker.com/linux/centos/docker-{{ docker_edition }}.repo
docker_yum_repo_enable_edge: 0
docker_yum_repo_enable_test: 0

docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present